 version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: elastic
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/conf.d
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/logstash-apache.json
        target: /var/log-template/logstash-apache.json
        read_only: true
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  webserver:
    build:
      context: apache/
    volumes:
      - type: bind
        source: ./apache/filebeat.yml
        target: /etc/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: ./apache/index.html
        target: /var/www/html/index.html
        read_only: true
      - type: bind
        source: ./apache/entrypoint.sh
        target: /app/entrypoint.sh
    entrypoint:
      - ./entrypoint.sh
    ports:
      - "80:80"
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
